In [3]:
my_list = [1,2,3]

In [1]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [13]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [24]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(5,5)

array([[0.88071887, 0.20618425, 0.53234571, 0.58107097, 0.10981909],
       [0.55125465, 0.12848203, 0.21452528, 0.93262791, 0.02886707],
       [0.89581957, 0.45962142, 0.19106957, 0.9774462 , 0.84478375],
       [0.32226715, 0.28894595, 0.47805903, 0.48990539, 0.28784163],
       [0.65600357, 0.18049858, 0.22557568, 0.09534791, 0.90082921]])

In [28]:
np.random.randn(2)

array([0.04635291, 1.02199125])

In [ ]:
np.random.randint(1,100,10)

array([16,  9,  4, 56, 72, 34, 44, 14, 89, 63])

In [32]:
ranarr = np.random.randint(0,50,10)

In [34]:
ranarr

array([33, 23, 35, 34, 33, 45,  2,  2, 26,  2])

In [ ]:
arr = np.arange(25)

In [40]:
arr = arr.reshape(5,5)

In [42]:
ranarr

array([33, 23, 35, 34, 33, 45,  2,  2, 26,  2])

In [44]:
ranarr.min()

np.int64(2)

In [46]:
ranarr.max()

np.int64(45)

In [49]:
ranarr.argmax()
ranarr[5]

np.int64(45)

In [50]:
arr.shape

(5, 5)

In [53]:
arr = np.arange(0,11)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr[8]

np.int64(8)

In [57]:
arr[1:5]

array([1, 2, 3, 4])

In [59]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [60]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [61]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [62]:
arr[0:5] = 100

In [63]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [65]:
slice_of_arr = arr[0:6]

In [67]:
slice_of_arr[:] = 99

In [68]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [2]:
import numpy as np

In [5]:
arr_2d = np.array(
    [
        [5,10,15],
        [20,25,30],
        [35,40,45]
    ]
)

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [7]:
arr_2d[0][0]

np.int64(5)

In [9]:
arr_2d[0,0]

np.int64(5)

In [18]:
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:

arr_2d[1:,::2]

array([[20, 30],
       [35, 45]])

In [21]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
bool_arr = arr > 5

In [24]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [25]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [26]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [29]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [30]:
1/0

ZeroDivisionError: division by zero

In [31]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr = np.arange(0,10)

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr/arr

/tmp/ipykernel_9077/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [36]:
1/arr

/tmp/ipykernel_9077/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [38]:
arr2 = arr/arr
arr3 = 1/arr

/tmp/ipykernel_9077/2305542074.py:1: RuntimeWarning: invalid value encountered in divide
  arr2 = arr/arr
/tmp/ipykernel_9077/2305542074.py:2: RuntimeWarning: divide by zero encountered in divide
  arr3 = 1/arr


In [39]:
arr2/arr3

array([nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [40]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [41]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [42]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])